"""empty message

Revision ID: 0a1daccf422d
Revises: 7a8ab7f82a28
Create Date: 2019-08-12 13:12:01.405305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a1daccf422d'
down_revision = '7a8ab7f82a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sensor_data_collection_number', table_name='sensor_data')
    op.drop_column('sensor_data', 'collection_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('collection_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('ix_sensor_data_collection_number', 'sensor_data', ['collection_number'], unique=False)
    # ### end Alembic commands ###
