"""empty message

Revision ID: 233e57f3aebe
Revises: e05accd5e962
Create Date: 2019-08-12 21:46:42.524801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233e57f3aebe'
down_revision = 'e05accd5e962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_summary', sa.Column('shaken', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_run_summary_shaken'), 'run_summary', ['shaken'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_summary_shaken'), table_name='run_summary')
    op.drop_column('run_summary', 'shaken')
    # ### end Alembic commands ###
