"""empty message

Revision ID: 29c450e9fd5c
Revises: 
Create Date: 2019-07-21 20:11:45.109577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c450e9fd5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pressure_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pressure_data_pressure'), 'pressure_data', ['pressure'], unique=False)
    op.create_index(op.f('ix_pressure_data_time_stamp'), 'pressure_data', ['time_stamp'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pressure_data_time_stamp'), table_name='pressure_data')
    op.drop_index(op.f('ix_pressure_data_pressure'), table_name='pressure_data')
    op.drop_table('pressure_data')
    # ### end Alembic commands ###
