"""empty message

Revision ID: 367e2d20261d
Revises: 9c732cedf07c
Create Date: 2019-08-27 16:23:04.751802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '367e2d20261d'
down_revision = '9c732cedf07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_summary', sa.Column('max_inflow', sa.Float(), nullable=True))
    op.alter_column('run_summary', 'good_coordination',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('run_summary', 'shaken',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.create_index(op.f('ix_run_summary_max_inflow'), 'run_summary', ['max_inflow'], unique=False)
    op.drop_index('ix_run_summary_avg_inflow', table_name='run_summary')
    op.drop_column('run_summary', 'avg_inflow')
    op.alter_column('sensor_data', 'pressure',
               existing_type=mysql.FLOAT(precision=9, scale=5),
               type_=sa.Float(precision='9,5'),
               existing_nullable=True)
    op.alter_column('sensor_data', 'proximity',
               existing_type=mysql.FLOAT(precision=9, scale=5),
               type_=sa.Float(precision='9,5'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor_data', 'proximity',
               existing_type=sa.Float(precision='9,5'),
               type_=mysql.FLOAT(precision=9, scale=5),
               existing_nullable=True)
    op.alter_column('sensor_data', 'pressure',
               existing_type=sa.Float(precision='9,5'),
               type_=mysql.FLOAT(precision=9, scale=5),
               existing_nullable=True)
    op.add_column('run_summary', sa.Column('avg_inflow', mysql.FLOAT(), nullable=True))
    op.create_index('ix_run_summary_avg_inflow', 'run_summary', ['avg_inflow'], unique=False)
    op.drop_index(op.f('ix_run_summary_max_inflow'), table_name='run_summary')
    op.alter_column('run_summary', 'shaken',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('run_summary', 'good_coordination',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('run_summary', 'max_inflow')
    # ### end Alembic commands ###
