"""empty message

Revision ID: 4561e52aa75b
Revises: 
Create Date: 2019-08-12 18:11:04.701547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4561e52aa75b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('actuation_time', sa.Float(), nullable=True),
    sa.Column('avg_inflow', sa.Float(), nullable=True),
    sa.Column('start_breath', sa.Float(), nullable=True),
    sa.Column('end_breath', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_summary_actuation_time'), 'run_summary', ['actuation_time'], unique=False)
    op.create_index(op.f('ix_run_summary_avg_inflow'), 'run_summary', ['avg_inflow'], unique=False)
    op.create_index(op.f('ix_run_summary_datetime'), 'run_summary', ['datetime'], unique=False)
    op.create_index(op.f('ix_run_summary_end_breath'), 'run_summary', ['end_breath'], unique=False)
    op.create_index(op.f('ix_run_summary_start_breath'), 'run_summary', ['start_breath'], unique=False)
    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actuation_id', sa.Integer(), nullable=True),
    sa.Column('time_stamp', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('proximity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['actuation_id'], ['run_summary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_data_pressure'), 'sensor_data', ['pressure'], unique=False)
    op.create_index(op.f('ix_sensor_data_proximity'), 'sensor_data', ['proximity'], unique=False)
    op.create_index(op.f('ix_sensor_data_time_stamp'), 'sensor_data', ['time_stamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_data_time_stamp'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_proximity'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_pressure'), table_name='sensor_data')
    op.drop_table('sensor_data')
    op.drop_index(op.f('ix_run_summary_start_breath'), table_name='run_summary')
    op.drop_index(op.f('ix_run_summary_end_breath'), table_name='run_summary')
    op.drop_index(op.f('ix_run_summary_datetime'), table_name='run_summary')
    op.drop_index(op.f('ix_run_summary_avg_inflow'), table_name='run_summary')
    op.drop_index(op.f('ix_run_summary_actuation_time'), table_name='run_summary')
    op.drop_table('run_summary')
    # ### end Alembic commands ###
