"""empty message

Revision ID: 48ebade8ffe0
Revises: 29c450e9fd5c
Create Date: 2019-07-21 20:24:37.340432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ebade8ffe0'
down_revision = '29c450e9fd5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pressure_data_time_stamp', table_name='pressure_data')
    op.create_index(op.f('ix_pressure_data_time_stamp'), 'pressure_data', ['time_stamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pressure_data_time_stamp'), table_name='pressure_data')
    op.create_index('ix_pressure_data_time_stamp', 'pressure_data', ['time_stamp'], unique=1)
    # ### end Alembic commands ###
