"""empty message

Revision ID: 7a8ab7f82a28
Revises: 
Create Date: 2019-08-05 15:35:41.548025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8ab7f82a28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_number', sa.Integer(), nullable=True),
    sa.Column('time_stamp', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('proximity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_data_collection_number'), 'sensor_data', ['collection_number'], unique=False)
    op.create_index(op.f('ix_sensor_data_pressure'), 'sensor_data', ['pressure'], unique=False)
    op.create_index(op.f('ix_sensor_data_proximity'), 'sensor_data', ['proximity'], unique=False)
    op.create_index(op.f('ix_sensor_data_time_stamp'), 'sensor_data', ['time_stamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_data_time_stamp'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_proximity'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_pressure'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_collection_number'), table_name='sensor_data')
    op.drop_table('sensor_data')
    # ### end Alembic commands ###
