"""empty message

Revision ID: e05accd5e962
Revises: 4561e52aa75b
Create Date: 2019-08-12 21:02:34.034716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e05accd5e962'
down_revision = '4561e52aa75b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('summary_id', sa.Integer(), nullable=True))
    op.drop_constraint('sensor_data_ibfk_1', 'sensor_data', type_='foreignkey')
    op.create_foreign_key(None, 'sensor_data', 'run_summary', ['summary_id'], ['id'])
    op.drop_column('sensor_data', 'actuation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('actuation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sensor_data', type_='foreignkey')
    op.create_foreign_key('sensor_data_ibfk_1', 'sensor_data', 'run_summary', ['actuation_id'], ['id'])
    op.drop_column('sensor_data', 'summary_id')
    # ### end Alembic commands ###
