"""empty message

Revision ID: f94adce4a607
Revises: 67417c1d42d4
Create Date: 2019-08-13 14:49:44.809799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f94adce4a607'
down_revision = '67417c1d42d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_summary', sa.Column('good_coordination', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_run_summary_good_coordination'), 'run_summary', ['good_coordination'], unique=False)
    op.drop_index('ix_run_summary_good_coordinatioon', table_name='run_summary')
    op.drop_column('run_summary', 'good_coordinatioon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_summary', sa.Column('good_coordinatioon', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index('ix_run_summary_good_coordinatioon', 'run_summary', ['good_coordinatioon'], unique=False)
    op.drop_index(op.f('ix_run_summary_good_coordination'), table_name='run_summary')
    op.drop_column('run_summary', 'good_coordination')
    # ### end Alembic commands ###
